"""initial migration

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-27
"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"
down_revision=None
branch_labels=None
depends_on=None

def upgrade()->None:
    op.create_table("topic", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("title", sa.String(), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_topic_title", "topic", ["title"], unique=True)
    op.create_table("user_profile", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("telegram_id", sa.BigInteger(), nullable=False), sa.Column("username", sa.String(255)), sa.Column("first_name", sa.String(255)), sa.Column("level", sa.Integer(), nullable=False, server_default="1"), sa.Column("xp", sa.Integer(), nullable=False, server_default="0"), sa.Column("current_streak", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_streak", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_activity_at", sa.DateTime(timezone=True)), sa.Column("selected_topic_id", sa.Integer(), sa.ForeignKey("topic.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_user_profile_telegram_id", "user_profile", ["telegram_id"], unique=True)
    op.create_table("task", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("topic_id", sa.Integer(), sa.ForeignKey("topic.id"), nullable=False), sa.Column("task_type", sa.String(), nullable=False), sa.Column("difficulty", sa.Integer(), nullable=False), sa.Column("question_text", sa.Text(), nullable=False), sa.Column("correct_answer", sa.String(), nullable=False), sa.Column("options", sa.JSON()), sa.Column("explanation", sa.Text(), nullable=False), sa.Column("source", sa.String(), nullable=False, server_default="seed"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_task_topic_id", "task", ["topic_id"]); op.create_index("ix_task_task_type", "task", ["task_type"]); op.create_index("ix_task_difficulty", "task", ["difficulty"])
    op.create_table("mastery_profile", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_profile.id"), nullable=False), sa.Column("topic_id", sa.Integer(), sa.ForeignKey("topic.id"), nullable=False), sa.Column("mastery_level", sa.Float(), nullable=False, server_default="0"), sa.Column("current_difficulty", sa.Integer(), nullable=False, server_default="1"), sa.Column("attempts_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("correct_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("error_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("average_answer_time", sa.Float(), nullable=False, server_default="0"), sa.Column("last_answer_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id","topic_id", name="uq_mastery_user_topic"))
    op.create_index("ix_mastery_profile_user_id", "mastery_profile", ["user_id"]); op.create_index("ix_mastery_profile_topic_id", "mastery_profile", ["topic_id"])
    op.create_table("task_log", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_profile.id"), nullable=False), sa.Column("task_id", sa.Integer(), sa.ForeignKey("task.id"), nullable=False), sa.Column("topic_id", sa.Integer(), sa.ForeignKey("topic.id"), nullable=False), sa.Column("task_type", sa.String(), nullable=False), sa.Column("difficulty", sa.Integer(), nullable=False), sa.Column("user_answer", sa.Text(), nullable=False), sa.Column("is_correct", sa.Boolean(), nullable=False), sa.Column("answer_time_seconds", sa.Float(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_task_log_user_id", "task_log", ["user_id"]); op.create_index("ix_task_log_task_id", "task_log", ["task_id"]); op.create_index("ix_task_log_topic_id", "task_log", ["topic_id"])
    op.create_table("gamification_log", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_profile.id"), nullable=False), sa.Column("event_type", sa.String(), nullable=False), sa.Column("xp_delta", sa.Integer(), nullable=False, server_default="0"), sa.Column("old_level", sa.Integer(), nullable=False, server_default="1"), sa.Column("new_level", sa.Integer(), nullable=False, server_default="1"), sa.Column("reason", sa.String(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("ix_gamification_log_user_id", "gamification_log", ["user_id"]); op.create_index("ix_gamification_log_event_type", "gamification_log", ["event_type"])
    op.create_table("achievement", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(), nullable=False), sa.Column("title", sa.String(), nullable=False), sa.Column("description", sa.String(), nullable=False), sa.Column("condition_type", sa.String(), nullable=False), sa.Column("condition_value", sa.Integer(), nullable=False), sa.Column("xp_reward", sa.Integer(), nullable=False, server_default="0"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_achievement_code", "achievement", ["code"], unique=True)
    op.create_table("user_achievement", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_profile.id"), nullable=False), sa.Column("achievement_id", sa.Integer(), sa.ForeignKey("achievement.id"), nullable=False), sa.Column("unlocked_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id","achievement_id", name="uq_user_achievement"))
    op.create_index("ix_user_achievement_user_id", "user_achievement", ["user_id"]); op.create_index("ix_user_achievement_achievement_id", "user_achievement", ["achievement_id"])
    op.create_table("quest", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(), nullable=False), sa.Column("title", sa.String(), nullable=False), sa.Column("description", sa.String(), nullable=False), sa.Column("quest_type", sa.String(), nullable=False), sa.Column("target_value", sa.Integer(), nullable=False), sa.Column("xp_reward", sa.Integer(), nullable=False, server_default="0"), sa.Column("topic_id", sa.Integer(), sa.ForeignKey("topic.id")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_quest_code", "quest", ["code"], unique=True); op.create_index("ix_quest_quest_type", "quest", ["quest_type"])
    op.create_table("user_quest", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user_profile.id"), nullable=False), sa.Column("quest_id", sa.Integer(), sa.ForeignKey("quest.id"), nullable=False), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("is_completed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id","quest_id", name="uq_user_quest"))
    op.create_index("ix_user_quest_user_id", "user_quest", ["user_id"]); op.create_index("ix_user_quest_quest_id", "user_quest", ["quest_id"])
    op.create_table("technical_log", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_type", sa.String(), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("latency_ms", sa.Float()), sa.Column("metadata", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index("ix_technical_log_event_type", "technical_log", ["event_type"])

def downgrade()->None:
    for name in ["technical_log","user_quest","quest","user_achievement","achievement","gamification_log","task_log","mastery_profile","task","user_profile","topic"]:
        op.drop_table(name)
